# render.yaml
# Configuration for deploying to Render.com

services:
  - type: web
    name: bundesliga-survivor
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn football_survivor_game.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.5"  # FIX: Specify Python 3.12 to work with psycopg2
      - key: DJANGO_SETTINGS_MODULE
        value: football_survivor_game.settings_production
      - key: SECRET_KEY
        generateValue: true
      - key: FOOTBALL_DATA_API_KEY
        sync: false  # You must add this manually in Render dashboard!
      # DATABASE_URL will be added manually after creating external database

# NOTE: Render's free plan doesn't auto-create databases from render.yaml
# You must either:
# 1. Create a PostgreSQL database manually in Render (expires in 90 days)
# 2. Use external database like Supabase or Neon (free, no expiration)
# Then add DATABASE_URL to environment variables above