# Generated by Django 5.1.12 on 2025-09-04 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=7, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminated', models.BooleanField(default=False)),
                ('eliminated_matchday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminations', to='survivor.matchday')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivor.gamepool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matchday',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivor.season'),
        ),
        migrations.AddField(
            model_name='gamepool',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivor.season'),
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_submitted', models.DateField()),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivor.matchday')),
                ('player_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivor.playerentry')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivor.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('result', models.CharField(blank=True, choices=[('HOME', 'Home Win'), ('AWAY', 'Away Win'), ('DRAW', 'Draw'), (None, 'Not Played')], max_length=4, null=True)),
                ('score', models.CharField(blank=True, max_length=5, null=True)),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survivor.matchday')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='survivor.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='survivor.team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matchday',
            unique_together={('season', 'number')},
        ),
    ]
