# Generated by Django 5.1.12 on 2025-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
