# Generated by Django 5.1.12 on 2025-09-05 12:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='playerentry',
            old_name='eliminated',
            new_name='is_eliminated',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pick_submitted',
        ),
        migrations.RemoveField(
            model_name='team',
            name='code',
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pick',
            name='is_successful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 9, 5, 12, 1, 3, 164489, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='color_primary',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='color_secondary',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='survivor.matchday'),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchdays', to='survivor.season'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='player_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='survivor.playerentry'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
