# Generated by Django 5.1.12 on 2025-09-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0002_alter_matchday_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
