# Generated by Django 5.1.12 on 2025-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0002_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
