# Generated by Django 5.1.12 on 2025-09-05 14:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0003_gamepool_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pick',
            options={'ordering': ['matchday__number']},
        ),
        migrations.AlterModelOptions(
            name='playerentry',
            options={'ordering': ['is_eliminated', '-eliminated_matchday__number', 'user__username']},
        ),
        migrations.RemoveField(
            model_name='gamepool',
            name='start_date',
        ),
        migrations.AddField(
            model_name='gamepool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 5, 14, 45, 56, 944857, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamepool',
            name='created_by',
            field=models.ForeignKey(default=datetime.datetime(2025, 9, 5, 14, 46, 8, 792859, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='created_pools', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerentry',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 5, 14, 46, 12, 488313, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamepool',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='survivor.season'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('HOME', 'Home Win'), ('AWAY', 'Away Win'), ('DRAW', 'Draw')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='survivor.matchday'),
        ),
        migrations.AlterField(
            model_name='playerentry',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='survivor.gamepool'),
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('player_entry', 'matchday')},
        ),
        migrations.AlterUniqueTogether(
            name='playerentry',
            unique_together={('user', 'pool')},
        ),
    ]
