# Generated by Django 5.1.12 on 2025-09-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0003_alter_matchday_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
