# Generated by Django 5.1.12 on 2025-09-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0004_match_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepool',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
